### ISSUE TITLE
Wrong download link on README.md

### ISSUE THREAD

**Issue by felipe-zampa** [replicatedhq/sbctl#102]
Section `Intel CPU / amd64` https://github.com/replicatedhq/sbctl#intel-cpu--amd64

Wrong command: `curl -LO https://github.com/replicatedhq/sbctl/releases/latest/download/sbctl_darwin_amd64.tar.gz`
Working command: `curl -LO https://github.com/replicatedhq/sbctl/releases/download/latest/sbctl_darwin_amd64.tar.gz`

--

Section `Apple M1 CPU / arm64` https://github.com/replicatedhq/sbctl#apple-m1-cpu--arm64

Wrong command: `curl -LO https://github.com/replicatedhq/sbctl/releases/latest/download/sbctl_darwin_arm64.tar.gz`
Working command: `curl -LO https://github.com/replicatedhq/sbctl/releases/download/latest/sbctl_darwin_arm64.tar.gz`

**Comment by danj-replicated** [comment]
Hi @felipe-zampa, it's interesting that the URL `https://github.com/replicatedhq/sbctl/releases/download/latest/sbctl_darwin_arm64.tar.gz` works for you because I get nothing but a 404, the original links however work fine. 

Are you able to share some console output or a screenshot of it not working?
